name: Discord CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
          YOUTUBE_SECRET: ${{ secrets.YOUTUBE_SECRET }}
          GPT_SECRET: ${{ secrets.GPT_SECRET }}
          
      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker --version
          docker build -t ${{ secrets.DOCKER_USERNAME }}/discordbotv3:latest --build-arg MAVEN_REPO=$HOME/.m2/repository -v $HOME/.m2:/root/.m2 .
          docker push ${{ secrets.DOCKER_USERNAME }}/discordbotv3:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get EC2 Instance IP
        run: |
          EC2_IP=$(aws ec2 describe-instances \
                    --filters "Name=instance-id,Values=${{ secrets.EC2_INSTANCE_ID }}" \
                    --query 'Reservations[0].Instances[0].PublicIpAddress' \
                    --output text)
          echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV


      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/discordbotv3:latest
            sudo docker stop discordbot || true
            sudo docker rm discordbot || true
            sudo docker run -d --name discordbot -p 8080:8080 \
              -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
              -e GUILD_ID=${{ secrets.GUILD_ID }} \
              -e OWNER_ID=${{ secrets.OWNER_ID }} \
              -e YOUTUBE_SECRET=${{ secrets.YOUTUBE_SECRET }} \
              -e GPT_SECRET=${{ secrets.GPT_SECRET }} \
              ${{ secrets.DOCKER_USERNAME }}/discordbotv3:latest
