name: Discord CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
          YOUTUBE_SECRET: ${{ secrets.YOUTUBE_SECRET }}
          GPT_SECRET: ${{ secrets.GPT_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/discordbotv4:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start SSH Agent and Add Key
        id: add_ssh_key
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          eval $(ssh-agent -s)
          echo "$SSH_PASSPHRASE" | ssh-add private_key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/discordbotv4:latest
            sudo docker stop discordbot || true
            sudo docker rm discordbot || true
            sudo docker run -d --name discordbot -p 8080:8080 \
              -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
              -e GUILD_ID=${{ secrets.GUILD_ID }} \
              -e OWNER_ID=${{ secrets.OWNER_ID }} \
              -e YOUTUBE_SECRET=${{ secrets.YOUTUBE_SECRET }} \
              -e GPT_SECRET=${{ secrets.GPT_SECRET }} \
              ${{ secrets.DOCKER_USERNAME }}/discordbotv4:latest

      - name: Cleanup
        run: rm private_key
